# Generated by Django 5.2.8 on 2025-11-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текст заголовка')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст сообщения')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя участника')),
                ('subscriber', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписчик')),
                ('organizer', models.BooleanField(blank=True, default=False, null=True, verbose_name='Организатор')),
                ('speaker', models.BooleanField(blank=True, default=False, null=True, verbose_name='Докладчик')),
                ('tg_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Место проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название мероприятия')),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('finish', models.DateTimeField(verbose_name='Дата оконания')),
                ('active', models.BooleanField(default=False, verbose_name='Мероприятие активно')),
                ('speaker', models.ManyToManyField(blank=True, default=None, related_name='events', to='meetbot.participant', verbose_name='докладчики')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='meetbot.place', verbose_name='Место проведения')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='Вопрос')),
                ('tg_chat_id', models.BigIntegerField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='meetbot.participant', verbose_name='Автор вопроса')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='meetbot.event', verbose_name='Доклад')),
            ],
        ),
    ]
