# Generated by Django 4.2.26 on 2025-12-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(verbose_name='Тема доклада')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewed', 'Рассмотрена')], default='new', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_applications', to='meetbot.event', verbose_name='Событие')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_applications', to='meetbot.participant', verbose_name='Заявитель')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
